# This file was generated by GoReleaser. DO NOT EDIT.
class Gopaniccheck < Formula
  desc "Go Panic Check"
  homepage "https://github.com/bflad/gopaniccheck"
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/bflad/gopaniccheck/releases/download/v0.1.0/gopaniccheck_0.1.0_darwin_amd64.tar.gz"
    sha256 "1a1249d7d4721ec921a403119ff64f8f469eb81c31abd7a3b085cf1442d25e54"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/bflad/gopaniccheck/releases/download/v0.1.0/gopaniccheck_0.1.0_linux_amd64.tar.gz"
      sha256 "b27ac6a71353ddc3fcb2d3a527c7fbde4a38df41093843d58c84416ad18752cc"
    end
  end
  
  depends_on "go"

  def install
    bin.install "gopaniccheck"
  end

  test do
    system "#{bin}/gopaniccheck -V"
  end
end
