# This file was generated by GoReleaser. DO NOT EDIT.
class Tfproviderdocs < Formula
  desc "Terraform Provider Documentation Tool"
  homepage "https://github.com/bflad/tfproviderdocs"
  version "0.4.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/bflad/tfproviderdocs/releases/download/v0.4.0/tfproviderdocs_0.4.0_darwin_amd64.tar.gz"
    sha256 "35ce861773cd1e97d7583be1a84d4140766e9fe63089881d4852e2ac92eb5783"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/bflad/tfproviderdocs/releases/download/v0.4.0/tfproviderdocs_0.4.0_linux_amd64.tar.gz"
      sha256 "a531b3d69de17a2c5b91c85aa519c92a06a924918f60c674eda639a316886005"
    end
  end
  
  depends_on "go"

  def install
    bin.install "tfproviderdocs"
  end

  test do
    system "#{bin}/tfproviderdocs -v"
  end
end
