# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfproviderlint < Formula
  desc "Terraform Provider Linter"
  homepage "https://github.com/bflad/tfproviderlint"
  version "0.24.0"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/bflad/tfproviderlint/releases/download/v0.24.0/tfproviderlint_0.24.0_darwin_amd64.tar.gz"
    sha256 "2fad3daaca9562b106a2c2378aebe52ad6a37314b0f07bff7fed9a8d0fc38f23"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/bflad/tfproviderlint/releases/download/v0.24.0/tfproviderlint_0.24.0_linux_amd64.tar.gz"
    sha256 "a82f2e1e30947882b57794717599a30fe053d735c26d72988cd46350f033a568"
  end

  depends_on "go"

  def install
    bin.install "tfproviderlint"
  end

  test do
    system "#{bin}/tfproviderlint -V"
  end
end
