# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfproviderlint < Formula
  desc "Terraform Provider Linter"
  homepage "https://github.com/bflad/tfproviderlint"
  version "0.23.0"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/bflad/tfproviderlint/releases/download/v0.23.0/tfproviderlint_0.23.0_darwin_amd64.tar.gz"
    sha256 "ab9cb8abb4367d2f4df9c668d62c5287b742845f3f05cf8985da2df01e13cbf7"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/bflad/tfproviderlint/releases/download/v0.23.0/tfproviderlint_0.23.0_linux_amd64.tar.gz"
    sha256 "1cb0eeb66e50c0c4898a3af776e8bc5f610fb95365bf471b67d7a5ad9b834233"
  end

  depends_on "go"

  def install
    bin.install "tfproviderlint"
  end

  test do
    system "#{bin}/tfproviderlint -V"
  end
end
