# This file was generated by GoReleaser. DO NOT EDIT.
class Tfproviderdocs < Formula
  desc "Terraform Provider Documentation Tool"
  homepage "https://github.com/bflad/tfproviderdocs"
  version "0.5.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/bflad/tfproviderdocs/releases/download/v0.5.2/tfproviderdocs_0.5.2_darwin_amd64.tar.gz"
    sha256 "ffe90b9638b88a562551a475f95e9efdf45543ebb973c7b19d8c07b520ed151a"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/bflad/tfproviderdocs/releases/download/v0.5.2/tfproviderdocs_0.5.2_linux_amd64.tar.gz"
      sha256 "7df1e95381c02f681ba98798fa542030881837c179811401ba1af773002de2b3"
    end
  end
  
  depends_on "go"

  def install
    bin.install "tfproviderdocs"
  end

  test do
    system "#{bin}/tfproviderdocs -v"
  end
end
