# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfproviderdocs < Formula
  desc "Terraform Provider Documentation Tool"
  homepage "https://github.com/bflad/tfproviderdocs"
  version "0.12.0"

  depends_on "go"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bflad/tfproviderdocs/releases/download/v0.12.0/tfproviderdocs_0.12.0_darwin_amd64.tar.gz"
      sha256 "1491045391e95091ae86f4d2293220d42c17c7981b71d78de27956207513ceb4"

      def install
        bin.install "tfproviderdocs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bflad/tfproviderdocs/releases/download/v0.12.0/tfproviderdocs_0.12.0_darwin_arm64.tar.gz"
      sha256 "e7063def18355be1a7ed69671b9d7efa801c492915c5c41fa0491ba589716ed7"

      def install
        bin.install "tfproviderdocs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bflad/tfproviderdocs/releases/download/v0.12.0/tfproviderdocs_0.12.0_linux_arm64.tar.gz"
      sha256 "85aa734ce177b0047e410c67ac82a05b5d8acf907176f45d70ff42642507590c"

      def install
        bin.install "tfproviderdocs"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bflad/tfproviderdocs/releases/download/v0.12.0/tfproviderdocs_0.12.0_linux_amd64.tar.gz"
      sha256 "7b6c14755dbfdde537540dd2f24bbaafe5ffce0b889ba4e3f1d4fb23760b239c"

      def install
        bin.install "tfproviderdocs"
      end
    end
  end

  test do
    system "#{bin}/tfproviderdocs -v"
  end
end
